import Head from "next/head";
import Navbar from "./components/Navbar/Navbar";
import Progress from "./components/progress/progress";
import { Inter } from "@next/font/google";
import BootstrapCarousel from "./components/carousel/Bootstrap";
import Services from "./components/Nos_services/Services";
import Footer from "./components/Footer";
import Projets from "./components/proj-main/projets";
import Blogs from "./components/Articles/Blogs";
import Titres from "./components/titres/titres";
import Partenariat from "./components/partenariat/partenariat";
import ProjetsRef from "./components/ProjetReferentPage/ProjetsRef";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="wrapper2">
          <Navbar />
          
          <BootstrapCarousel />

          <Progress/>

          <Titres text="Découvrir nos services"/>
          
          <Services />
          <Titres text="Nos projets réferents"/>
          <Projets />
         
          <Titres text="Pour savoir plus sur l'energie solaire vous pouvez lire ces articles"/>
          <Blogs/><Titres text="NOS PARTENAIRES"/>

          <Partenariat/>
         
          <Footer />
         
        </div>
      </main>
    </>
  );
}
