import Head from "next/head";
// import styles from '../styles/Home.module.css'
import styles from "../styles/secondPage.module.scss";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer";
import { items } from "./components/ArticlePage/item";
import Partenariat from "./components/partenariat/partenariat";
import ImageArticle from "./components/imageArticle/imageArticle";
import Carousel from "react-bootstrap/Carousel";

const imgg1 = new URL("../../public/assets/IMG_blog1.jpg", import.meta.url);
export default function SecondPageProjet(id) {
  const router = useRouter();
  var id1 = router.query.id;
  const [projet, setProjet] = useState();
  var myObject = items.find((item) => item.id1 === id1);
  console.log(myObject);

  useEffect(() => {
    //use id to get article Data from back
    setProjet(items[id1 - 1]);
  }, [id1]);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <div className={styles.flex_container_page}>
        {/* <h2 className={styles.titre}>{myObject.title}</h2>
        <div className={styles.article}>{myObject.content}</div>
        <img className={styles.image1} src={myObject.image} /> */}
{projet ? (
  <div> 
    {projet.titre}
    {projet.description}
    {projet.type}
    
  </div>
):null}

        <button
          className={styles.btnR}
          onClick={() => {
            router.back();
          }}>
          {" "}
          Retour
        </button>
      </div>
      <Footer />
    </div>
  );
}
