  import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect } from 'react'
import { useRouter } from 'next/router'
const imgg1 = new URL("../../public/assets/IMG_blog1.jpg",import.meta.url)
export default function SecondPageArticle() {
  const router = useRouter()
  const id = router.query.id
  useEffect(() => {
    //use id to get article Data from back
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2 className={styles.titre} >Energie photovoltaïque : Avantages et inconvénients</h2>
      <main className={styles.body}>
        <div className={styles.image1}>
          <img src={imgg1} ></img>
        </div>

        <div className={styles.article}>

          <p>Energie photovoltaïque en Tunisie: quelles sont les avantages et inconvénients.
            Lorsque l'on parle de l'énergie photovoltaïque, on pense d'abord à l'énergie solaire. Malheureusement, l'énergie solaire ne représente que 3,2% de l'énergie produite en Tunisie. L'énergie photovoltaïque représente donc la grande majorité de l'énergie solaire. Cette énergie est produite par des panneaux photovoltaïques fixés sur un toit ou sur un terrain.
          </p>

          <h4 className={styles.titre1}>1. L'énergie solaire en Tunisie</h4>

          <p>
            L'énergie solaire en Tunisie L'énergie solaire en Tunisie est une source d'énergie renouvelable avec l'énergie éolienne. Les avantages et inconvénients de l'énergie solaire en Tunisie se trouvent dans les avantages et inconvénients de l'énergie éolienne. L'énergie solaire en Tunisie est une source d'énergie renouvelable avec l'énergie éolienne. Les avantages et inconvénients de l'énergie solaire en Tunisie se trouvent dans les avantages et inconvénients de l'énergie éolienne.
            <h4 className={styles.titre1}>2. L'énergie photovoltaïque</h4>
            L'énergie photovoltaïque est une énergie renouvelable qui peut être produite à partir d'une surface plane d'un bâtiment. Celle-ci est produite par des cellules solaires photovoltaïques qui captent la lumière solaire et la convertissent en électricité. L'énergie photovoltaïque est gratuite et renouvelable. Elle peut être utilisée pour fournir de l'électricité à une maison, un bureau ou une usine. L'avantage de l'énergie photovoltaïque est qu'il est facile d'en racheter et qu'il est peu coûteux. L'inconvénient de l'énergie photovoltaïque est qu'il est difficile de la maintenir à un niveau constant.
          </p>

          <h4 className={styles.titre1}>3. Le coût de l'énergie</h4>
          <p>
            L'énergie photovoltaïque est une énergie renouvelable qui est produite grâce à la lumière du soleil. Elle est plus fiable et moins chère que l'énergie électrique. L'énergie photovoltaïque peut être produite à partir de sources d'énergie renouvelables telles que la pluie, le vent, et le soleil. L'énergie photovoltaïque est plus propre et ne génère pas d'émissions de gaz à effet de serre. L'énergie photovoltaïque est aussi plus durable et économique car elle peut être stockée longtemps. Les avantages de l'énergie photovoltaïque sont donc nombreux et elle est devenue une énergie de référence.
          </p>

          <h4 className={styles.titre1} >4. Conclusion.</h4>
          <p>
            Les avantages de l'énergie photovoltaïque -L'énergie photovoltaïque est un mode de production d'énergie renouvelable, donc elle est exempte de pollution.
            <ul >
              <li>Elle est économique, puisque l'investissement est faible et les coûts d'exploitation sont bas. </li>
              <li>Elle est également économique pour les gens qui n'ont pas accès à l'électricité.</li>
              <li>L'énergie photovoltaïque garantit une certaine autonomie énergétique.</li>
              <li>L'énergie photovoltaïque garantit une certaine autonomie énergétique.</li>
              <li>L'énergie photovoltaïque garantit une certaine autonomie énergétique.</li>
              <li>Elle permet de faire des économies en énergie. </li>
            </ul>
          </p>
        </div>
        <button className={styles.btnR} onClick={() => {
          router.back()
        }}> Retour</button>
      </main>
    </>
  )
}
