import Head from "next/head";
// import styles from '../styles/Home.module.css'
import styles from "../styles/secondPage.module.scss";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer";
import Partenariat from "./components/partenariat/partenariat";
import ImageArticle from "./components/imageArticle/imageArticle";
const imgg1 = new URL("../../public/assets/IMG_blog1.jpg", import.meta.url);
export default function SecondPageArticle({data}) {
    const router = useRouter();
    const PROTOCOL_AND_HOST_NAME_PART_OF_THE_URL = 'http://localhost:5050'
    const [article, setArticle] = useState([]);

    useEffect(() => {
        fetch(`${PROTOCOL_AND_HOST_NAME_PART_OF_THE_URL}/article/${data.id}`)
            .then(response => response.json())
            .then(data => {
                console.log('hedhi idata', data);
                setArticle(data);
            }).catch(error => console.log(error));

    }, []);

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />

            <div className={styles.flex_container_page}>
                {/* <h2 className={styles.titre}>{myObject.title}</h2>
        <div className={styles.article}>{myObject.content}</div>
        <img className={styles.image1} src={myObject.image} /> */}

                <button
                    className={styles.btnR}
                    onClick={() => {
                        router.back();
                    }}>
                    {" "}
                    Retour
                </button>
            </div>
            <Footer />
        </div>
    );
}
SecondPageArticle.getInitialProps = async ({ query }) => {
    const data = query;

    return { data };
};

