import Head from "next/head";
// import styles from '../styles/Home.module.css'
import styles from "../styles/secondPage.module.scss";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer";
import { items } from "./components/ArticlePage/item";
import Partenariat from "./components/partenariat/partenariat";
import ImageArticle from "./components/imageArticle/imageArticle";
import Carousel from "react-bootstrap/Carousel";

const imgg1 = new URL("../../public/assets/IMG_blog1.jpg", import.meta.url);
const Gallery = ({ imagePaths }) => {
  if(!Array.isArray(imagePaths)){imagePaths=[imagePaths]}
  return (
    <div className="gallery">
      {imagePaths.map(path => (
        <img key={path} src={`http://localhost:5050/imagesProjet/${path}`} alt={path} />
      ))}
    </div>
  );
};
export default function SecondPageProjet({data}) {
  const router = useRouter();
  const PROTOCOL_AND_HOST_NAME_PART_OF_THE_URL = 'http://localhost:5050'
  const [projet, setprojet] = useState([]);

  useEffect(() => {
      fetch(`${PROTOCOL_AND_HOST_NAME_PART_OF_THE_URL}/projet/${data.id}`)
          .then(response => response.json())
          .then(data => {
              console.log('hedhi idata', data);
              setprojet(data);
          }).catch(error => console.log(error));

  }, []);
useEffect(()=>{
      console.log('hedha projet', projet)
      console.log('hetha taille imta3 tableau images', projet?.images?.length)
  },[projet]);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

 
      <div className={styles.flex_container_page}>
                
                <h2 className={styles.titre}>{projet.titre}</h2>
       <div className={styles.article}>{projet.contenu}</div>
       
       <img  className={styles.image1} src={`${PROTOCOL_AND_HOST_NAME_PART_OF_THE_URL}/imagesprojet/${Array.isArray(projet?.images)? projet.images[0]:projet.images}`} /> 
           
    
   
   <h2 className={styles.titre}>
   {projet.titre}
   </h2>

   <div className="row justify-content-center">
      
       
       <div className=" col-sm-12 col-md-6">
       <p className={styles.article}>
       {projet.contenu}
         </p>      
       </div>
       <Gallery imagePaths={projet.images}></Gallery>

        <button
          className={styles.btnR}
          onClick={() => {
            router.back();
          }}>
          {" "}
          Retour
        </button>
      </div>
      </div>
      <Footer />
    </div>
  );
}
SecondPageProjet.getInitialProps = async ({ query }) => {
  const data = query;

  return { data };
};
